### ISSUE TITLE
Add "Recover password" link on login form's design

### ISSUE THREAD

**Issue by rubennp** [IT-Academy-BCN/ita-directory#306]
Añadir al prototipo de la página de login enlace a "recuperar la contraseña" presente en el proyecto.

<img width="332" alt="Captura de Pantalla 2021-10-18 a les 12 46 55" src="https://user-images.githubusercontent.com/8426157/137717201-97edf524-bb2b-44e2-87ec-df4abf1cc834.png">

**Comment by adaldin** [comment]
![Captura de pantalla 2022-11-21 a la(s) 08 49 27](https://user-images.githubusercontent.com/18453013/202994215-5a2f4cbf-c95a-4f36-9d5e-d2cfae168078.png)
Login link added and working
