### ISSUE TITLE
Add change password page

### ISSUE THREAD

**Issue by kevinmamaqi** [IT-Academy-BCN/ita-directory#511]

**Comment by adaldin** [comment]
Displaying change password page.
Missing from backend:
-On requesting 'recover-password', a 'status 500 error' appears on console:
POST http://localhost:10910/api/v1/recover-password 500 (Internal Server Error)
-On the fetch/XHR 'recover-password':
message : "\nInvalid prisma.user.findUnique()

linked to issue # 721 Fix recover password request on ITA-API
