### ISSUE TITLE
Fix login access

### ISSUE THREAD

**Issue by adaldin** [IT-Academy-BCN/ita-directory#731]
Not possible to log in
Trying to log in on, throws an error on server with status 500, and message 'Invalid `prisma.user.findUnique()' on users.controller.js
![Captura de Pantalla 2022-10-05 a la(s) 11 59 43](https://user-images.githubusercontent.com/18453013/194034614-04960444-9765-42f6-a61a-2924de0de176.png)

**Comment by tonikny** [comment]
It was an configuration error. Solved.
