### ISSUE TITLE
Fix Contact Modal

### ISSUE THREAD

**Issue by RogerRochoRibas** [IT-Academy-BCN/ita-directory#795]
- Message Field is different from Name and Email
- Does not show Error messages

**Comment by rabbanirizwan** [comment]
@RogerRochoRibas  can I work on it?

**Comment by RogerRochoRibas** [comment]
@rabbanirizwan Sure, tell me if you need more info on the issue.

**Comment by rabbanirizwan** [comment]
@RogerRochoRibas can you tell me how can I reproduce this

**Comment by RogerRochoRibas** [comment]
@rabbanirizwan You can see the Contact Modal by going to /ads (must log in, access data is in seed.js) and clicking any of the contact buttons.

**Comment by rabbanirizwan** [comment]
<img width="772" alt="Screenshot 2022-11-15 at 8 05 56 PM" src="https://user-images.githubusercontent.com/33807776/201953571-1efca3e5-f7b0-4f00-bc7d-2280796e0430.png">

it is okay?

**Comment by RogerRochoRibas** [comment]
Looks great.
Is it showing error messages? for example if you click send without filling the fields or don't enter a valid email address.

**Comment by rabbanirizwan** [comment]
<img width="758" alt="Screenshot 2022-11-24 at 6 55 18 PM" src="https://user-images.githubusercontent.com/33807776/203801504-2bffe85f-5977-4218-9a83-51bce3f5ad10.png">
<img width="667" alt="Screenshot 2022-11-24 at 6 56 58 PM" src="https://user-images.githubusercontent.com/33807776/203801734-4f99a8b3-8f6a-477c-af8e-a6379bdd883e.png">

Yes it is

**Comment by kevinmamaqi** [comment]
Create the pr for review @rabbanirizwan
