### ISSUE TITLE
Allow to update password from user profile

### ISSUE THREAD

**Issue by kevinmamaqi** [IT-Academy-BCN/ita-directory#824]
<img width="660" alt="Screenshot 2022-11-23 at 09 21 15" src="https://user-images.githubusercontent.com/972664/203499769-d541f51a-ff90-4c41-bb64-2f810e257235.png">

**Comment by rabbanirizwan** [comment]
kindly assign this to me

**Comment by adaldin** [comment]
> kindly assign this to me

@rabbanirizwan I will be working in this issue if you don't mind.

Thanks for supporting us!
